global:
  scrape_interval: 100s

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['host.docker.internal:8000']

  - job_name: 'mlflow'
    static_configs:
      - targets: ['host.docker.internal:5000']