version: '3.8'

services:
  angular-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taxi-predictor-angular
    ports:
      - "4200:4200"
    volumes:
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm start"
